from .base import StageDefinition, make_stage


def build_stage() -> StageDefinition:
    return make_stage(
        stage_id="regressions_water_pricing",
        display_name="Regressions Water Pricing",
        category="regression",
        stata_script="Regressions_Water_pricing.do",
        description="Estimate the OECD water pricing regressions and correlations.",
        dependencies=("format_aquastat", "format_pwt", "format_wb"),
        expected_outputs=(
            "tables/Freshwater_Prices.xls",
            "tables/V2020_2008_Freshwater_Prices.xls",
            "tables/TableA2.smcl",
        ),
        notes=(
            "Graph 6 is not generated by code in the public package.",
            "Use the OECD document referenced in README.pdf for the manual reconstruction.",
        ),
    )
