local CountryV "CountryN"

replace `CountryV'="USA" if `CountryV'=="UNITED STATES OF AMERICA"
replace `CountryV'="USA" if `CountryV'=="US"

replace `CountryV'="Cote d'Ivoire" if `CountryV'=="Côte d'Ivoire"
replace `CountryV'="China" if `CountryV'=="China, People's Republic of" //joinby `CountryV' using "$path4//country_list.dta", unmatched(both) update
replace `CountryV'="USA" if `CountryV'=="United States"
replace `CountryV'="Slovakia" if `CountryV'=="Slovak Republic"
replace `CountryV'="euroarea" if `CountryV'=="European Union" 
replace `CountryV'="Armenia" if `CountryV'=="Armenia, Republic of"
replace `CountryV'="FYR Macedonia" if `CountryV'=="Macedonia, FYR"
replace `CountryV'="Kosovo" if `CountryV'=="Kosovo, Republic of"
replace `CountryV'="Korea, Republic of" if `CountryV'=="Korea, Rep."
replace `CountryV'="Hong Kong SAR" if `CountryV'=="Hong Kong SAR, China"
replace `CountryV'="S Korea" if `CountryV'=="Korea, Republic of"
replace `CountryV'="Afghanistan" if `CountryV'=="Afghanistan, Islamic Republic of"
replace `CountryV'="Azerbaijan" if `CountryV'=="Azerbaijan, Republic of"
replace `CountryV'="Bahrain" if `CountryV'=="Bahrain, Kingdom of"
replace `CountryV'="Hong Kong" if `CountryV'=="China, P.R.: Hong Kong"
replace `CountryV'="Hong Kong" if `CountryV'=="Hong Kong SAR"
replace `CountryV'="Macao" if `CountryV'=="China, P.R.: Macao"
replace `CountryV'="Macao" if `CountryV'=="Macao SAR, China"
replace `CountryV'="China" if `CountryV'=="China, P.R.: Mainland"
replace `CountryV'="Congo, Dem. Rep." if `CountryV'=="Congo, Democratic Republic of"
replace `CountryV'="Congo, Rep." if `CountryV'=="Congo, Republic of"
replace `CountryV'="Egypt" if `CountryV'=="Egypt, Arab Rep."
replace `CountryV'="Eswatini" if `CountryV'=="Eswatini, Kingdom of"
replace `CountryV'="Euro area" if `CountryV'=="Euro Area"
replace `CountryV'="Euro area" if `CountryV'=="euroarea"
replace `CountryV'="Iran" if `CountryV'=="Iran, Islamic Rep."
replace `CountryV'="Iran" if `CountryV'=="Iran, Islamic Republic of"
replace `CountryV'="Lao" if `CountryV'=="Lao PDR"
replace `CountryV'="Lao" if `CountryV'=="Lao People's Democratic Republic"
replace `CountryV'="Micronesia" if `CountryV'=="Micronesia, Fed. Sts."
replace `CountryV'="Micronesia" if `CountryV'=="Micronesia, Federated States of"
replace `CountryV'="North Macedonia" if `CountryV'=="North Macedonia, Republic of"
replace `CountryV'="Serbia" if `CountryV'=="Serbia, Republic of"
replace `CountryV'="Timor-Leste" if `CountryV'=="Timor-Leste, Dem. Rep. of"
replace `CountryV'="Venezuela" if `CountryV'=="Venezuela, RB"
replace `CountryV'="Venezuela" if `CountryV'=="Venezuela, República Bolivariana de"
replace `CountryV'="Venezuela" if `CountryV'=="Venezuela, Republica Bolivariana de"
replace `CountryV'="Yemen" if `CountryV'=="Yemen, Rep."
replace `CountryV'="Yemen" if `CountryV'=="Yemen, Republic of"	
replace `CountryV'="Bahamas" if `CountryV'=="Bahamas, The"	
replace `CountryV'="Bolivia" if `CountryV'=="Bolivia (Plurinational State of)"	
replace `CountryV'="Hong Kong" if `CountryV'=="China, Hong Kong SAR"	
replace `CountryV'="Macao" if `CountryV'=="China, Macao SAR"	
replace `CountryV'="Taiwan" if `CountryV'=="China, Taiwan Province"	
replace `CountryV'="Curaçao" if `CountryV'=="Curacao"
replace `CountryV'="Gambia" if `CountryV'=="Gambia, The"
replace `CountryV'="Czech Republic" if `CountryV'=="Czechia"	
replace `CountryV'="Iran" if `CountryV'=="Iran (Islamic Republic of)"
replace `CountryV'="N Korea" if `CountryV'=="Korea, Dem. People’s Rep."
replace `CountryV'="Kyrgyzstan" if `CountryV'=="Kyrgyz Republic"
replace `CountryV'="Lao" if `CountryV'=="Lao People's Dem Rep"
replace `CountryV'="S Korea" if `CountryV'=="Republic of Korea"
replace `CountryV'="Moldova" if `CountryV'=="Republic of Moldova"
replace `CountryV'="USA" if `CountryV'=="United States of America"
replace `CountryV'="USA" if `CountryV'=="United States"
replace `CountryV'="Tanzania" if `CountryV'=="United Republic of Tanzania"
replace `CountryV'="Venezuela" if `CountryV'=="Venezuela (Bolivarian Republic of)"
replace `CountryV'="Vietnam" if `CountryV'=="Viet Nam"
replace `CountryV'="São Tomé and Príncipe" if `CountryV'=="Sao Tome and Principe"
replace `CountryV'="Cabo Verde" if `CountryV'=="Cape Verde"
replace `CountryV'="Congo, Dem. Rep." if `CountryV'=="Democratic Republic of the Congo"
replace `CountryV'="North Macedonia" if `CountryV'=="FYR Macedonia"
replace `CountryV'="N Korea" if `CountryV'=="Korea, Democratic People's Republic of"
replace `CountryV'="Moldova" if `CountryV'=="Moldova, Republic of"
replace `CountryV'="St. Martin (French part)" if `CountryV'=="Saint Martin (French part)"
replace `CountryV'="St. Kitts and Nevis" if `CountryV'=="Saint Kitts and Nevis"
replace `CountryV'="St. Vincent and the Grenadines" if `CountryV'=="Saint Vincent and the Grenadines"
replace `CountryV'="Palestine" if `CountryV'=="Palestine, State of"
replace `CountryV'="Palestine" if `CountryV'=="State of Palestine"
replace `CountryV'="Virgin Islands (U.S.)" if `CountryV'=="US Virgin Islands"
replace `CountryV'="Palestine" if `CountryV'=="West Bank and Gaza"
replace `CountryV'="Virgin Islands, British" if `CountryV'=="British Virgin Islands"
replace `CountryV'="St. Lucia" if `CountryV'=="Saint Lucia"
replace `CountryV'="Eswatini" if `CountryV'=="Swaziland"
capture replace `CountryV'="Congo, Rep." if `CountryV'=="Congo" & CountryCode==178 //capture replace `CountryV'="Congo, Dem. Rep." if `CountryV'=="Congo"
capture replace `CountryV'="Congo, Rep." if `CountryV'=="Congo"
capture replace `CountryV'="Turkey" if CountryN=="Türkiye"

replace `CountryV'="Czech Republic" if `CountryV'=="Czechoslovakia"	//  //   //   Attention!
replace `CountryV'="Germany" if `CountryV'=="Germany, Fed Rep"	//  //   //   Attention!
replace `CountryV'="Ethiopia" if `CountryV'=="Ethiopia and Eritrea"	//  //   //   Attention!
replace `CountryV'="Serbia" if `CountryV'=="Serbia and Montenegro"	//  //   //   Attention!

replace `CountryV' = strproper(`CountryV') if `CountryV'!="USA" & `CountryV'!="UK"
