from __future__ import annotations

from pathlib import PurePosixPath

from .types import ArtifactSpec, ExhibitSpec


def _artifact(relative_path: str, description: str = "") -> ArtifactSpec:
    return ArtifactSpec(relative_path=relative_path, description=description)


EXHIBITS: tuple[ExhibitSpec, ...] = (
    ExhibitSpec(
        exhibit_id="figure_1",
        paper_label="Figure 1",
        section="main",
        status_in_report="Results reproduced, but the paper figure includes manual changes from code output.",
        manual_changes_expected=True,
        actual_artifacts=(_artifact("graphs/Fig1_water_pc.png"),),
        report_aliases=(),
        notes=("Canonical package artifact is the PNG export generated by Graph1_example.do.",),
        verification_mode="required",
    ),
    ExhibitSpec(
        exhibit_id="figure_2",
        paper_label="Figure 2",
        section="main",
        status_in_report="Results reproduced, but the paper figure includes manual changes from code output.",
        manual_changes_expected=True,
        actual_artifacts=(_artifact("graphs/Fig2_daily_water_use_per_capita.png"),),
        report_aliases=("Fig2_daily_water_use_per_capita.png",),
        notes=(),
        verification_mode="required",
    ),
    ExhibitSpec(
        exhibit_id="figure_3",
        paper_label="Figure 3",
        section="main",
        status_in_report="Results reproduced, but the paper figure includes manual changes from code output.",
        manual_changes_expected=True,
        actual_artifacts=(_artifact("graphs/Fig3_WaterStress_SectorsSDG.png"),),
        report_aliases=("Fig3vs1_WaterStress_Sectors.png",),
        notes=("The active code path generates the SDG-labeled Figure 3 PNG.",),
        verification_mode="required",
    ),
    ExhibitSpec(
        exhibit_id="figure_4",
        paper_label="Figure 4",
        section="main",
        status_in_report="Results reproduced, but the paper figure includes manual changes from code output.",
        manual_changes_expected=True,
        actual_artifacts=(_artifact("graphs/Fig4_WaterStress_WB.png"),),
        report_aliases=("Fig4_WaterStress_WB.png",),
        notes=(),
        verification_mode="required",
    ),
    ExhibitSpec(
        exhibit_id="figure_5",
        paper_label="Figure 5",
        section="main",
        status_in_report="Results reproduced, but the paper figure includes manual changes from code output.",
        manual_changes_expected=True,
        actual_artifacts=(_artifact("Fig5_WaterStress_2000_2020_WB.png"),),
        report_aliases=("Fig5_WaterStress_2000_2020_WB.png",),
        notes=("Figure 5 is exported to the Outputs root rather than Outputs/graphs.",),
        verification_mode="required",
    ),
    ExhibitSpec(
        exhibit_id="figure_6",
        paper_label="Figure 6",
        section="main",
        status_in_report="Does not apply.",
        manual_changes_expected=False,
        actual_artifacts=(),
        report_aliases=(),
        notes=("Graph 6 was built manually in Excel from OECD values and is outside coded replication.",),
        verification_mode="not_applicable",
    ),
    ExhibitSpec(
        exhibit_id="table_1",
        paper_label="Table 1",
        section="main",
        status_in_report="Results reproduced, but the paper table includes manual changes from code output.",
        manual_changes_expected=True,
        actual_artifacts=(
            _artifact("tables/Water_pop_gdp.xls"),
            _artifact("tables/Water_demand_2050.xlsx"),
        ),
        report_aliases=("Water_pop_gdp.xls", "Water_demand_2050.xlsx"),
        notes=(),
        verification_mode="required",
    ),
    ExhibitSpec(
        exhibit_id="table_2",
        paper_label="Table 2",
        section="main",
        status_in_report="Reproduced.",
        manual_changes_expected=False,
        actual_artifacts=(_artifact("tables/SummaryStats.xls"),),
        report_aliases=("SummaryStats.xls",),
        notes=(),
        verification_mode="required",
    ),
    ExhibitSpec(
        exhibit_id="table_3",
        paper_label="Table 3",
        section="main",
        status_in_report="Results reproduced, but the paper table includes manual changes from code output.",
        manual_changes_expected=True,
        actual_artifacts=(_artifact("tables/Table3_GDPgr.xls"),),
        report_aliases=("GDPgr.xls",),
        notes=(),
        verification_mode="required",
    ),
    ExhibitSpec(
        exhibit_id="table_4",
        paper_label="Table 4",
        section="main",
        status_in_report="Results reproduced, but the paper table includes manual changes from code output.",
        manual_changes_expected=True,
        actual_artifacts=(_artifact("tables/Table4_Investment.xls"),),
        report_aliases=("Investment.xls",),
        notes=(),
        verification_mode="required",
    ),
    ExhibitSpec(
        exhibit_id="table_5",
        paper_label="Table 5",
        section="main",
        status_in_report="Results reproduced, but the paper table includes manual changes from code output.",
        manual_changes_expected=True,
        actual_artifacts=(_artifact("tables/Table5_CPI.xls"),),
        report_aliases=("GDPgr.xls",),
        notes=("The report cites GDPgr.xls for Table 5, but the package output is Table5_CPI.xls.",),
        verification_mode="required",
    ),
    ExhibitSpec(
        exhibit_id="table_6",
        paper_label="Table 6",
        section="main",
        status_in_report="Results reproduced, but the paper table includes manual changes from code output.",
        manual_changes_expected=True,
        actual_artifacts=(_artifact("tables/Table6.smcl"),),
        report_aliases=("Table6.smcl",),
        notes=(),
        verification_mode="required",
    ),
    ExhibitSpec(
        exhibit_id="table_7",
        paper_label="Table 7",
        section="main",
        status_in_report="Results reproduced, but the paper table includes manual changes from code output.",
        manual_changes_expected=True,
        actual_artifacts=(_artifact("tables/Agr_Ind_Services_gr.xls"),),
        report_aliases=("Agr_Ind_Services_gr.xls",),
        notes=(),
        verification_mode="required",
    ),
    ExhibitSpec(
        exhibit_id="table_8",
        paper_label="Table 8",
        section="main",
        status_in_report="Results reproduced, but the paper table includes manual changes from code output.",
        manual_changes_expected=True,
        actual_artifacts=(
            _artifact("tables/IIP_gr.xls"),
            _artifact("tables/Automotive_gr.xls"),
        ),
        report_aliases=("IIP_gr.xls", "Automotive_gr.xls"),
        notes=(),
        verification_mode="required",
    ),
    ExhibitSpec(
        exhibit_id="figure_a1",
        paper_label="Figure A1",
        section="annex",
        status_in_report="Results reproduced, but the paper figure includes manual changes from code output.",
        manual_changes_expected=True,
        actual_artifacts=(_artifact("graphs/FigA1_USDm3.png"),),
        report_aliases=("FigA1_USDm3.png",),
        notes=(),
        verification_mode="required",
    ),
    ExhibitSpec(
        exhibit_id="figure_a2",
        paper_label="Figure A2",
        section="annex",
        status_in_report="Results reproduced, but the paper figure includes manual changes from code output.",
        manual_changes_expected=True,
        actual_artifacts=(_artifact("graphs/FigA2_USDm3_Sectors.png"),),
        report_aliases=("FigA2_USDm3_Sectors.png",),
        notes=(),
        verification_mode="required",
    ),
    ExhibitSpec(
        exhibit_id="table_a1",
        paper_label="Table A1",
        section="annex",
        status_in_report="Reproduced.",
        manual_changes_expected=False,
        actual_artifacts=(_artifact("tables/ListCountries_Water.xlsx"),),
        report_aliases=("ListCountries_Water.xlsx",),
        notes=(),
        verification_mode="required",
    ),
    ExhibitSpec(
        exhibit_id="table_a2",
        paper_label="Table A2",
        section="annex",
        status_in_report="Results reproduced, but the paper table includes manual changes from code output.",
        manual_changes_expected=True,
        actual_artifacts=(_artifact("tables/TableA2.smcl"),),
        report_aliases=("TableA2.smcl",),
        notes=(),
        verification_mode="required",
    ),
    ExhibitSpec(
        exhibit_id="table_a3",
        paper_label="Table A3",
        section="annex",
        status_in_report="Reproduced.",
        manual_changes_expected=False,
        actual_artifacts=(_artifact("tables/Freshwater_Prices.xls"),),
        report_aliases=("Freshwater_Prices.xls",),
        notes=("The stage also produces V2020_2008_Freshwater_Prices.xls as a supplementary code output.",),
        verification_mode="required",
    ),
    ExhibitSpec(
        exhibit_id="table_a4",
        paper_label="Table A4",
        section="annex",
        status_in_report="Reproduced.",
        manual_changes_expected=False,
        actual_artifacts=(
            _artifact("tables/PWT_level.xls"),
            _artifact("tables/PWT_growth.xls"),
            _artifact("tables/GDPgr_PWT.xls"),
            _artifact("tables/Investmentgr_PWT.xls"),
        ),
        report_aliases=(),
        notes=("Canonical appendix mapping follows the package README, not the inconsistent report numbering.",),
        verification_mode="required",
    ),
    ExhibitSpec(
        exhibit_id="table_a5",
        paper_label="Table A5",
        section="annex",
        status_in_report="Reproduced.",
        manual_changes_expected=False,
        actual_artifacts=(
            _artifact("tables/GDPgr_QR25.xls"),
            _artifact("tables/GDPgr_QR50.xls"),
            _artifact("tables/GDPgr_QR75.xls"),
        ),
        report_aliases=(),
        notes=("Canonical appendix mapping follows the package README, not the inconsistent report numbering.",),
        verification_mode="required",
    ),
    ExhibitSpec(
        exhibit_id="table_a6",
        paper_label="Table A6",
        section="annex",
        status_in_report="Reproduced.",
        manual_changes_expected=False,
        actual_artifacts=(_artifact("tables/Electricity.xls"),),
        report_aliases=(),
        notes=("Canonical appendix mapping follows the package README, not the inconsistent report numbering.",),
        verification_mode="required",
    ),
    ExhibitSpec(
        exhibit_id="table_a7",
        paper_label="Table A7",
        section="annex",
        status_in_report="Reproduced.",
        manual_changes_expected=False,
        actual_artifacts=(
            _artifact("tables/Food_NatResR_QR25.xls"),
            _artifact("tables/Food_NatResR_QR50.xls"),
            _artifact("tables/Food_NatResR_QR75.xls"),
        ),
        report_aliases=(),
        notes=("Canonical appendix mapping follows the package README, not the inconsistent report numbering.",),
        verification_mode="required",
    ),
    ExhibitSpec(
        exhibit_id="table_a8",
        paper_label="Table A8",
        section="annex",
        status_in_report="Reproduced.",
        manual_changes_expected=False,
        actual_artifacts=(
            _artifact("tables/Investment_QR25.xls"),
            _artifact("tables/Investment_QR50.xls"),
            _artifact("tables/Investment_QR75.xls"),
        ),
        report_aliases=(),
        notes=("Canonical appendix mapping follows the package README, not the inconsistent report numbering.",),
        verification_mode="required",
    ),
)

KNOWN_ALIAS_ANOMALIES: dict[tuple[str, str], dict[str, object]] = {
    ("figure_3", "Fig3vs1_WaterStress_Sectors.png"): {
        "canonical_targets": ("graphs/Fig3_WaterStress_SectorsSDG.png",),
        "message": "The report references Fig3vs1_WaterStress_Sectors.png, but the active package output is Fig3_WaterStress_SectorsSDG.png.",
    },
    ("table_3", "GDPgr.xls"): {
        "canonical_targets": ("tables/Table3_GDPgr.xls",),
        "message": "The report references GDPgr.xls, but the package output is Table3_GDPgr.xls.",
    },
    ("table_4", "Investment.xls"): {
        "canonical_targets": ("tables/Table4_Investment.xls",),
        "message": "The report references Investment.xls, but the package output is Table4_Investment.xls.",
    },
    ("table_5", "GDPgr.xls"): {
        "canonical_targets": ("tables/Table5_CPI.xls",),
        "message": "The report references GDPgr.xls for Table 5, but the package output is Table5_CPI.xls.",
    },
}

GENERAL_ANOMALIES: tuple[dict[str, object], ...] = (
    {
        "anomaly_id": "appendix-numbering-inconsistency",
        "severity": "warning",
        "message": "The World Bank report appendix exhibit numbering is inconsistent with the README/package output mapping. The verifier follows the README/package canonical mapping for Tables A4-A8.",
    },
    {
        "anomaly_id": "graph-6-manual-excel",
        "severity": "warning",
        "message": "Graph 6 is intentionally absent from coded outputs because the public package says it was created manually in Excel from OECD values.",
    },
    {
        "anomaly_id": "macos-emf-portability",
        "severity": "warning",
        "message": "Stata on macOS does not generate EMF files. PNG exports are the canonical graph outputs on this machine.",
    },
)


def canonical_artifact_paths() -> tuple[str, ...]:
    paths = [artifact.normalized_path for exhibit in EXHIBITS for artifact in exhibit.actual_artifacts]
    return tuple(paths)


def normalized_canonical_paths() -> tuple[str, ...]:
    return tuple(dict.fromkeys(canonical_artifact_paths()))


def get_known_alias_anomaly(exhibit_id: str, alias: str) -> dict[str, object] | None:
    return KNOWN_ALIAS_ANOMALIES.get((exhibit_id, PurePosixPath(alias).name))


def validate_reference_manifest(strict_doc_aliases: bool = False) -> tuple[str, ...]:
    issues: list[str] = []
    seen_paths: set[str] = set()
    for exhibit in EXHIBITS:
        if exhibit.verification_mode == "required" and not exhibit.actual_artifacts:
            issues.append(f"{exhibit.exhibit_id} is required but has no canonical artifacts.")
        canonical_basenames = {artifact.basename for artifact in exhibit.actual_artifacts}
        for artifact in exhibit.actual_artifacts:
            normalized = artifact.normalized_path
            if PurePosixPath(normalized).is_absolute():
                issues.append(f"{exhibit.exhibit_id} uses an absolute artifact path: {normalized}")
            if ".." in PurePosixPath(normalized).parts:
                issues.append(f"{exhibit.exhibit_id} uses a non-normalized artifact path: {normalized}")
            if normalized in seen_paths:
                issues.append(f"Duplicate canonical artifact path detected: {normalized}")
            seen_paths.add(normalized)
        for alias in exhibit.report_aliases:
            alias_name = PurePosixPath(alias).name
            if alias_name in canonical_basenames:
                continue
            if strict_doc_aliases:
                issues.append(
                    f"{exhibit.exhibit_id} alias {alias_name} does not match a canonical artifact under strict alias mode."
                )
                continue
            if get_known_alias_anomaly(exhibit.exhibit_id, alias_name) is None:
                issues.append(f"{exhibit.exhibit_id} alias {alias_name} is not covered by the anomaly catalog.")
    return tuple(issues)
